import SeaterCar from '../../assets/img/car1.svg';
import MainCar from '../../assets/img/toppng.svg';
import SuitCaseCar from '../../assets/img/briefcase.svg';
import CarType from '../../assets/img/virus.svg';
import ACCar from '../../assets/img/airC.svg'
export const TripData = [
  {
    id: 1,
    startingPoint: "Lagos",
    destination: "Benin",
    price: "100000",
    discountPrice: "50000",
    availabilityStatus: "Available",
    carImg: MainCar,
    noOfSeaterCar: 5,
    noOfSuitCases: 4,
    acAvailibility: "AC Available",
    carType: "Automatic",
    distance: 10.7,
    travelTime: "10",
    totalTrips: 58,
    noOfSeaterCarImg: SeaterCar,
    noOfSuitCasesImg: SuitCaseCar,
    acAvailibilityImg: ACCar,
    carTypeUrl: CarType,
    carCategory: "small",
    terminal: "ikorodu",
    status: "available"
  },
  {
    id: 2,
    startingPoint: "Abuja",
    destination: "Kano",
    price: "20000",
    discountPrice: "5000",
    availabilityStatus: "Not Available",
    carImg: MainCar,
    noOfSeaterCar: 3,
    noOfSuitCases: 1,
    acAvailibility: "AC Not Available",
    carType: "Manual",
    distance: 15.7,
    travelTime: "19",
    totalTrips: 34,
    noOfSeaterCarImg: SeaterCar,
    noOfSuitCasesImg: SuitCaseCar,
    acAvailibilityImg: ACCar,
    carTypeUrl: CarType,
    carCategory: "medium"
  },
  {
    id: 3,
    startingPoint: "Ibadan",
    destination: "Niger",
    price: "150000",
    discountPrice: "100000",
    availabilityStatus: "Available",
    carImg: MainCar,
    noOfSeaterCar: 12,
    noOfSuitCases: 6,
    acAvailibility: "AC Available",
    carType: "Automatic",
    distance: 10.7,
    travelTime: "10",
    totalTrips: 58,
    noOfSeaterCarImg: SeaterCar,
    noOfSuitCasesImg: SuitCaseCar,
    acAvailibilityImg: ACCar,
    carTypeUrl: CarType,
    carCategory: "large"
  },
  {
    id: 4,
    startingPoint: "Ibadan",
    destination: "Niger",
    price: "150000",
    discountPrice: "100000",
    availabilityStatus: "On Route",
    carImg: MainCar,
    noOfSeaterCar: 12,
    noOfSuitCases: 6,
    acAvailibility: "AC Available",
    carType: "Automatic",
    distance: 10.7,
    travelTime: "10",
    totalTrips: 58,
    noOfSeaterCarImg: SeaterCar,
    noOfSuitCasesImg: SuitCaseCar,
    acAvailibilityImg: ACCar,
    carTypeUrl: CarType,
    carCategory: "premium"
  },
  {
    id: 5,
    startingPoint: "Abuja",
    destination: "Kano",
    price: "820000",
    discountPrice: "5000",
    availabilityStatus: "Available",
    carImg: MainCar,
    noOfSeaterCar: 3,
    noOfSuitCases: 1,
    acAvailibility: "AC Not Available",
    carType: "Manual",
    distance: 15.7,
    travelTime: "19",
    totalTrips: 34,
    noOfSeaterCarImg: SeaterCar,
    noOfSuitCasesImg: SuitCaseCar,
    acAvailibilityImg: ACCar,
    carTypeUrl: CarType,
    carCategory: "suv"
  },
  {
    id: 6,
    startingPoint: "Lagos",
    destination: "Benin",
    price: "100000",
    discountPrice: "50000",
    availabilityStatus: "Available",
    carImg: MainCar,
    noOfSeaterCar: 5,
    noOfSuitCases: 4,
    acAvailibility: "AC Available",
    carType: "Automatic",
    distance: 10.7,
    travelTime: "10",
    totalTrips: 58,
    noOfSeaterCarImg: SeaterCar,
    noOfSuitCasesImg: SuitCaseCar,
    acAvailibilityImg: ACCar,
    carTypeUrl: CarType,
    carCategory: "small",
    terminal: "ikorodu",
    status: "available"
  },
  {
    id: 7,
    startingPoint: "Abuja",
    destination: "Kano",
    price: "20000",
    discountPrice: "5000",
    availabilityStatus: "Not Available",
    carImg: MainCar,
    noOfSeaterCar: 3,
    noOfSuitCases: 1,
    acAvailibility: "AC Not Available",
    carType: "Manual",
    distance: 15.7,
    travelTime: "19",
    totalTrips: 34,
    noOfSeaterCarImg: SeaterCar,
    noOfSuitCasesImg: SuitCaseCar,
    acAvailibilityImg: ACCar,
    carTypeUrl: CarType,
    carCategory: "medium"
  },
  {
    id: 8,
    startingPoint: "Ibadan",
    destination: "Niger",
    price: "150000",
    discountPrice: "100000",
    availabilityStatus: "Available",
    carImg: MainCar,
    noOfSeaterCar: 12,
    noOfSuitCases: 6,
    acAvailibility: "AC Available",
    carType: "Automatic",
    distance: 10.7,
    travelTime: "10",
    totalTrips: 58,
    noOfSeaterCarImg: SeaterCar,
    noOfSuitCasesImg: SuitCaseCar,
    acAvailibilityImg: ACCar,
    carTypeUrl: CarType,
    carCategory: "large"
  },
  {
    id: 9,
    startingPoint: "Ibadan",
    destination: "Niger",
    price: "150000",
    discountPrice: "100000",
    availabilityStatus: "On Route",
    carImg: MainCar,
    noOfSeaterCar: 12,
    noOfSuitCases: 6,
    acAvailibility: "AC Available",
    carType: "Automatic",
    distance: 10.7,
    travelTime: "10",
    totalTrips: 58,
    noOfSeaterCarImg: SeaterCar,
    noOfSuitCasesImg: SuitCaseCar,
    acAvailibilityImg: ACCar,
    carTypeUrl: CarType,
    carCategory: "premium"
  },
  {
    id: 10,
    startingPoint: "Abuja",
    destination: "Kano",
    price: "20000",
    discountPrice: "5000",
    availabilityStatus: "Not Available",
    carImg: MainCar,
    noOfSeaterCar: 3,
    noOfSuitCases: 1,
    acAvailibility: "AC Not Available",
    carType: "Manual",
    distance: 15.7,
    travelTime: "19",
    totalTrips: 34,
    noOfSeaterCarImg: SeaterCar,
    noOfSuitCasesImg: SuitCaseCar,
    acAvailibilityImg: ACCar,
    carTypeUrl: CarType,
    carCategory: "suv"
  },

]