const bookingsTypes = {
	CREATE_BOOKINGS_ERROR: 'CREATE_BOOKINGS_ERROR',
	CREATE_BOOKINGS_SUCCESS: 'CREATE_BOOKINGS_SUCCESS',
	CREATE_BOOKINGS_LOADING: 'CREATE_BOOKINGS_LOADING',
	CLEAR_CREATE_BOOKINGS_ERRORS: 'CLEAR_CREATE_BOOKINGS_ERRORS',

	FILTER_BOOKINGS_ERROR: 'FILTER_BOOKINGS_ERROR',
	FILTER_BOOKINGS_SUCCESS: 'FILTER_BOOKINGS_SUCCESS',
	FILTER_BOOKINGS_LOADING: 'FILTER_BOOKINGS_LOADING',
	CLEAR_FILTER_BOOKINGS_ERRORS: 'CLEAR_FILTER_BOOKINGS_ERRORS',

	UPDATE_BOOKINGS_ERROR: 'UPDATE_BOOKINGS_ERROR',
	UPDATE_BOOKINGS_SUCCESS: 'UPDATE_BOOKINGS_SUCCESS',
	UPDATE_BOOKINGS_LOADING: 'UPDATE_BOOKINGS_LOADING',
	CLEAR_UPDATE_BOOKINGS_ERRORS: 'CLEAR_UPDATE_BOOKINGS_ERRORS',

	FETCH_ALL_BOOKINGS_ERROR: 'FETCH_ALL_BOOKINGS_ERROR',
	FETCH_ALL_BOOKINGS_SUCCESS: 'FETCH_ALL_BOOKINGS_SUCCESS',
	FETCH_ALL_BOOKINGS_LOADING: 'FETCH_ALL_BOOKINGS_LOADING',
	CLEAR_FETCH_ALL_BOOKINGS_ERRORS: 'CLEAR_FETCH_ALL_BOOKINGS_ERRORS',

	FETCH_SINGLE_BOOKING_ERROR: 'FETCH_SINGLE_BOOKING_ERROR',
	FETCH_SINGLE_BOOKING_SUCCESS: 'FETCH_SINGLE_BOOKING_SUCCESS',
	FETCH_SINGLE_BOOKING_LOADING: 'FETCH_SINGLE_BOOKING_LOADING',
	CLEAR_FETCH_SINGLE_BOOKING_ERRORS: 'CLEAR_FETCH_SINGLE_BOOKING_ERRORS'
};

export default bookingsTypes;
