const businessDetailsTypes = {
  BUSINESS_DETAILS_ERROR: 'BUSINESS_DETAILS_ERROR',
  BUSINESS_DETAILS_SUCCESS: 'BUSINESS_DETAILS_SUCCESS',
  BUSINESS_DETAILS_LOADING: 'BUSINESS_DETAILS_LOADING',
  CLEAR_BUSINESS_DETAILS_ERRORS: 'CLEAR_BUSINESS_DETAILS_ERRORS',
};

export default businessDetailsTypes;

