const customerTypes = {
	GET_CUSTOMER_ERROR: 'GET_CUSTOMER_ERROR',
	GET_CUSTOMER_SUCCESS: 'GET_CUSTOMER_SUCCESS',
	GET_CUSTOMER_LOADING: 'GET_CUSTOMER_LOADING',
	CLEAR_CUSTOMER_ERRORS: 'CLEAR_CUSTOMER_ERRORS',

	ADD_CUSTOMER_ERROR: 'ADD_CUSTOMER_ERROR',
	ADD_CUSTOMER_LOADING: 'ADD_CUSTOMER_LOADING',
	ADD_CUSTOMER_SUCCESS: 'ADD_CUSTOMER_SUCCESS',

	EDIT_CUSTOMER_ERROR: 'EDIT_CUSTOMER_ERROR',
	EDIT_CUSTOMER_LOADING: 'EDIT_CUSTOMER_LOADING',
	EDIT_CUSTOMER_SUCCESS: 'EDIT_CUSTOMER_SUCCESS',

	ACTIVATE_CUSTOMER_LOADING: 'ACTIVATE_CUSTOMER_LOADING',
	ACTIVATE_CUSTOMER_SUCCESS: 'ACTIVATE_CUSTOMER_SUCCESS',
	ACTIVATE_CUSTOMER_ERROR: 'ACTIVATE_CUSTOMER_ERROR',

	DEACTIVATE_CUSTOMER_LOADING: 'DEACTIVATE_CUSTOMER_LOADING',
	DEACTIVATE_CUSTOMER_SUCCESS: 'DEACTIVATE_CUSTOMER_SUCCESS',
	DEACTIVATE_CUSTOMER_ERROR: 'DEACTIVATE_CUSTOMER_ERROR',

	FETCH_CUSTOMER_SAVED_TRIPS_LOADING: 'FETCH_CUSTOMER_SAVED_TRIPS_LOADING',
	FETCH_CUSTOMER_SAVED_TRIPS_SUCCESS: 'FETCH_CUSTOMER_SAVED_TRIPS_SUCCESS',
	FETCH_CUSTOMER_SAVED_TRIPS_ERROR: 'FETCH_CUSTOMER_SAVED_TRIPS_ERROR',

	GET_SINGLE_CUSTOMER_ERROR: 'GET_SINGLE_CUSTOMER_ERROR',
	GET_SINGLE_CUSTOMER_SUCCESS: 'GET_SINGLE_CUSTOMER_SUCCESS',
	GET_SINGLE_CUSTOMER_LOADING: 'GET_SINGLE_CUSTOMER_LOADING',
	CLEAR_SINGLE_CUSTOMER_ERRORS: 'CLEAR_SINGLE_CUSTOMER_ERRORS'
};

export default customerTypes;
