
const loginTypes = {
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_LOADING: 'LOGIN_LOADING',
  CLEAR_LOGIN_ERRORS: 'CLEAR_LOGIN_ERRORS',
  LOG_OUT_USER: 'LOG_USER_OUT',
};

export default loginTypes;
