const loginTypes = {
	LOGIN_ERROR: 'LOGIN_ERROR',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_LOADING: 'LOGIN_LOADING',
	CLEAR_LOGIN_ERRORS: 'CLEAR_LOGIN_ERRORS',
	LOG_OUT_USER: 'LOG_USER_OUT',
	TOKEN_SUCCESS: 'TOKEN_SUCCESS',
	GET_USER_LOADING: 'GET_USER_LOADING',
	GET_USER_SUCCESS: 'GET_USER_SUCCESS',
	GET_USER_ERROR: 'GET_USER_ERROR',
	UPDATE_USER_LOADING: 'UPDATE_USER_LOADING',
	UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
	UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',
	UPDATE_PASSWORD_LOADING: 'UPDATE_PASSWORD_LOADING',
	UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
	UPDATE_PASSWORD_ERROR: 'UPDATE_PASSWORD_ERROR',
	UPDATE_IMAGE_LOADING: 'UPDATE_IMAGE_LOADING',
	UPDATE_IMAGE_SUCCESS: 'UPDATE_IMAGE_SUCCESS',
	UPDATE_IMAGE_ERROR: 'UPDATE_IMAGE_ERROR'
};

export default loginTypes;
