const loginTypes = {
	LOGIN_ERROR: 'LOGIN_ERROR',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_LOADING: 'LOGIN_LOADING',
	CLEAR_LOGIN_ERRORS: 'CLEAR_LOGIN_ERRORS',
	LOG_OUT_USER: 'LOG_USER_OUT',
	TOKEN_SUCCESS: 'TOKEN_SUCCESS'
};

export default loginTypes;
