const permitSubmissionTypes = {
	PERMIT_SUBMISSION_ERROR: 'PERMIT_SUBMISSION_ERROR',
	PERMIT_SUBMISSION_SUCCESS: 'PERMIT_SUBMISSION_SUCCESS',
	PERMIT_SUBMISSION_LOADING: 'PERMIT_SUBMISSION_LOADING',
	CLEAR_PERMIT_SUBMISSION_ERRORS: 'CLEAR_PERMIT_SUBMISSION_ERRORS'
};

export default permitSubmissionTypes;
