
const promoCodesTypes = {
  CREATE_PROMO_CODES_ERROR: 'CREATE_PROMO_CODES_ERROR',
  CREATE_PROMO_CODES_SUCCESS: 'CREATE_PROMO_CODES_SUCCESS',
  CREATE_PROMO_CODES_LOADING: 'CREATE_PROMO_CODES_LOADING',
  CLEAR_CREATE_PROMO_CODES_ERRORS: 'CLEAR_CREATE_PROMO_CODES_ERRORS',

  UPDATE_PROMO_CODES_ERROR: 'UPDATE_PROMO_CODES_ERROR',
  UPDATE_PROMO_CODES_SUCCESS: 'UPDATE_PROMO_CODES_SUCCESS',
  UPDATE_PROMO_CODES_LOADING: 'UPDATE_PROMO_CODES_LOADING',
  CLEAR_UPDATE_PROMO_CODES_ERRORS: 'CLEAR_UPDATE_PROMO_CODES_ERRORS',

  FETCH_ALL_PROMO_CODES_ERROR: 'FETCH_ALL_PROMO_CODES_ERROR',
  FETCH_ALL_PROMO_CODES_SUCCESS: 'FETCH_ALL_PROMO_CODES_SUCCESS',
  FETCH_ALL_PROMO_CODES_LOADING: 'FETCH_ALL_PROMO_CODES_LOADING',
  CLEAR_FETCH_ALL_PROMO_CODES_ERRORS: 'CLEAR_FETCH_ALL_PROMO_CODES_ERRORS',

  FETCH_SINGLE_PROMO_CODES_ERROR: 'FETCH_SINGLE_PROMO_CODES_ERROR',
  FETCH_SINGLE_PROMO_CODES_SUCCESS: 'FETCH_SINGLE_PROMO_CODES_SUCCESS',
  FETCH_SINGLE_PROMO_CODES_LOADING: 'FETCH_SINGLE_PROMO_CODES_LOADING',
  CLEAR_FETCH_SINGLE_PROMO_CODES_ERRORS: 'CLEAR_FETCH_SINGLE_PROMO_CODES_ERRORS',
};

export default promoCodesTypes;
