const registerTypes = {
  REGISTER_ERROR: 'REGISTER_ERROR',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_LOADING: 'REGISTER_LOADING',
  CLEAR_REGISTER_ERRORS: 'CLEAR_REGISTER_ERRORS',
};

export default registerTypes;

