const staffTypes = {
	GET_STAFF_ERROR: 'GET_STAFF_ERROR',
	GET_STAFF_SUCCESS: 'GET_STAFF_SUCCESS',
	GET_STAFF_LOADING: 'GET_STAFF_LOADING',
	CLEAR_STAFF_ERRORS: 'CLEAR_STAFF_ERRORS',

	ADD_STAFF_ERROR: 'ADD_STAFF_ERROR',
	ADD_STAFF_LOADING: 'ADD_STAFF_LOADING',
	ADD_STAFF_SUCCESS: 'ADD_STAFF_SUCCESS',

	EDIT_STAFF_ERROR: 'EDIT_STAFF_ERROR',
	EDIT_STAFF_LOADING: 'EDIT_STAFF_LOADING',
	EDIT_STAFF_SUCCESS: 'EDIT_STAFF_SUCCESS',

	ACTIVATE_STAFF_LOADING: 'ACTIVATE_STAFF_LOADING',
	ACTIVATE_STAFF_SUCCESS: 'ACTIVATE_STAFF_SUCCESS',
	ACTIVATE_STAFF_ERROR: 'ACTIVATE_STAFF_ERROR',

	DEACTIVATE_STAFF_LOADING: 'DEACTIVATE_STAFF_LOADING',
	DEACTIVATE_STAFF_SUCCESS: 'DEACTIVATE_STAFF_SUCCESS',
	DEACTIVATE_STAFF_ERROR: 'DEACTIVATE_STAFF_ERROR',

	GET_SINGLE_STAFF_ERROR: 'GET_SINGLE_STAFF_ERROR',
	GET_SINGLE_STAFF_SUCCESS: 'GET_SINGLE_STAFF_SUCCESS',
	GET_SINGLE_STAFF_LOADING: 'GET_SINGLE_STAFF_LOADING',
	CLEAR_SINGLE_STAFF_ERRORS: 'CLEAR_SINGLE_STAFF_ERRORS'
};

export default staffTypes;
