const terminalsTypes = {
	GET_TERMINALS_ERROR: 'GET_TERMINALS_ERROR',
	GET_TERMINALS_SUCCESS: 'GET_TERMINALS_SUCCESS',
	GET_TERMINALS_LOADING: 'GET_TERMINALS_LOADING',
	CLEAR_TERMINALS_ERRORS: 'CLEAR_TERMINALS_ERRORS',

	ADD_TERMINALS_ERROR: 'ADD_TERMINALS_ERROR',
	ADD_TERMINALS_LOADING: 'ADD_TERMINALS_LOADING',
	ADD_TERMINALS_SUCCESS: 'ADD_TERMINALS_SUCCESS',

	EDIT_TERMINALS_ERROR: 'EDIT_TERMINALS_ERROR',
	EDIT_TERMINALS_LOADING: 'EDIT_TERMINALS_LOADING',
	EDIT_TERMINALS_SUCCESS: 'EDIT_TERMINALS_SUCCESS'
};

export default terminalsTypes;
