const transportTypes = {
	TRANSPORT_TYPE_ERROR: 'TRANSPORT_TYPE_ERROR',
	TRANSPORT_TYPE_SUCCESS: 'TRANSPORT_TYPE_SUCCESS',
	TRANSPORT_TYPE_LOADING: 'TRANSPORT_TYPE_LOADING',
	CLEAR_TRANSPORT_TYPE_ERRORS: 'CLEAR_TRANSPORT_TYPE_ERRORS'
};

export default transportTypes;
