
const tripsTypes = {
    CREATE_TRIPS_ERROR: 'CREATE_TRIPS_ERROR',
    CREATE_TRIPS_SUCCESS: 'CREATE_TRIPS_SUCCESS',
    CREATE_TRIPS_LOADING: 'CREATE_TRIPS_LOADING',
    CLEAR_CREATE_TRIPS_ERRORS: 'CLEAR_CREATE_TRIPS_ERRORS',
  
    UPDATE_TRIPS_ERROR: 'UPDATE_TRIPS_ERROR',
    UPDATE_TRIPS_SUCCESS: 'UPDATE_TRIPS_SUCCESS',
    UPDATE_TRIPS_LOADING: 'UPDATE_TRIPS_LOADING',
    CLEAR_UPDATE_TRIPS_ERRORS: 'CLEAR_UPDATE_TRIPS_ERRORS',
  
    FETCH_ALL_TRIPS_ERROR: 'FETCH_ALL_TRIPS_ERROR',
    FETCH_ALL_TRIPS_SUCCESS: 'FETCH_ALL_TRIPS_SUCCESS',
    FETCH_ALL_TRIPS_LOADING: 'FETCH_ALL_TRIPS_LOADING',
    CLEAR_FETCH_ALL_TRIPS_ERRORS: 'CLEAR_FETCH_ALL_TRIPS_ERRORS',
  
    FETCH_SINGLE_TRIP_ERROR: 'FETCH_SINGLE_TRIP_ERROR',
    FETCH_SINGLE_TRIP_SUCCESS: 'FETCH_SINGLE_TRIP_SUCCESS',
    FETCH_SINGLE_TRIP_LOADING: 'FETCH_SINGLE_TRIP_LOADING',
    CLEAR_FETCH_SINGLE_TRIP_ERRORS: 'CLEAR_FETCH_SINGLE_TRIP_ERRORS',
  };
  
  export default tripsTypes;
  