const vehiclesTypes = {
	CREATE_VEHICLE_ERROR: 'CREATE_VEHICLE_ERROR',
	CREATE_VEHICLE_SUCCESS: 'CREATE_VEHICLE_SUCCESS',
	CREATE_VEHICLE_LOADING: 'CREATE_VEHICLE_LOADING',
	CLEAR_CREATE_VEHICLE_ERRORS: 'CLEAR_CREATE_VEHICLE_ERRORS',

	UPDATE_VEHICLE_ERROR: 'UPDATE_VEHICLE_ERROR',
	UPDATE_VEHICLE_SUCCESS: 'UPDATE_VEHICLE_SUCCESS',
	UPDATE_VEHICLE_LOADING: 'UPDATE_VEHICLE_LOADING',
	CLEAR_UPDATE_VEHICLE_ERRORS: 'CLEAR_UPDATE_VEHICLE_ERRORS',

	FETCH_ALL_VEHICLES_ERROR: 'FETCH_ALL_VEHICLES_ERROR',
	FETCH_ALL_VEHICLES_SUCCESS: 'FETCH_ALL_VEHICLES_SUCCESS',
	FETCH_ALL_VEHICLES_LOADING: 'FETCH_ALL_VEHICLES_LOADING',
	CLEAR_FETCH_ALL_VEHICLES_ERRORS: 'CLEAR_FETCH_ALL_VEHICLES_ERRORS',

	FETCH_SINGLE_VEHICLE_ERROR: 'FETCH_SINGLE_VEHICLE_ERROR',
	FETCH_SINGLE_VEHICLE_SUCCESS: 'FETCH_SINGLE_VEHICLE_SUCCESS',
	FETCH_SINGLE_VEHICLE_LOADING: 'FETCH_SINGLE_VEHICLE_LOADING',
	CLEAR_FETCH_SINGLE_VEHICLE_ERRORS: 'CLEAR_FETCH_SINGLE_VEHICLE_ERRORS'
};

export default vehiclesTypes;
