const verifyEmailTypes = {
	VERIFY_EMAIL_ERROR: 'VERIFY_EMAIL_ERROR',
	VERIFY_EMAIL_SUCCESS: 'VERIFY_EMAIL_SUCCESS',
	VERIFY_EMAIL_LOADING: 'VERIFY_EMAIL_LOADING',
	VERIFY_EMAIL_ERRFLAG: 'VERIFY_EMAIL_ERRFLAG',
	CLEAR_VERIFY_EMAIL_ERRORS: 'CLEAR_VERIFY_EMAIL_ERRORS'
};

export default verifyEmailTypes;
